language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
before_install:
   - composer require phpunit/phpunit:5.5.* satooshi/php-coveralls:1.0.*
   - composer install --dev
after_success:
  - php vendor/bin/coveralls -v